import { CardDeclarable, DeclarationSide, IDScope } from "#/declarations/ExplicitDeclaration";
import { DeclarableProperty, NullableStringDeclarableProperty } from "#/declarations/Declarable";

export class CardDeclaration implements CardDeclarable {
	[key: string]: DeclarableProperty;
	public deckID: NullableStringDeclarableProperty;

	public readonly id: string;
	public readonly side: DeclarationSide;

	public readonly isAutoGenerated: boolean = false;
	public readonly idScope: IDScope;

	public constructor(id: string, side: DeclarationSide, idScope: IDScope, deckID: string | null = null, isAutoGenerated: boolean) {
		this.id = id;
		this.side = side;
		this.idScope = idScope;
		this.deckID = deckID;
		this.isAutoGenerated = isAutoGenerated;
	}
}
